
export const musicalKeys: string[] = [
  'Do Mayor',
  'Do menor',
  'Do# / Reb Mayor',
  'Do# / Reb menor',
  'Re Mayor',
  'Re menor',
  'Re# / Mib Mayor',
  'Re# / Mib menor',
  'Mi Mayor',
  'Mi menor',
  'Fa Mayor',
  'Fa menor',
  'Fa# / Solb Mayor',
  'Fa# / Solb menor',
  'Sol Mayor',
  'Sol menor',
  'Sol# / Lab Mayor',
  'Sol# / Lab menor',
  'La Mayor',
  'La menor',
  'La# / Sib Mayor',
  'La# / Sib menor',
  'Si Mayor',
  'Si menor',
];
